version: '3.8'

services:
  # --- Cache Redis ---
  redis:
    image: redis:alpine
    container_name: appprodutos-redis
    ports:
      - "6379:6379"
    restart: always

  # --- Interface Redis (Opcional) ---
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

# Volume para persistÃªncia de dados do Postgres
volumes:
  postgres_data: